### PR TITLE
Fix async issue and rename html element classes

### LINKED ISSUE #20: DRY up welcome message in `generateUser`
**What is the proposed feature? Please describe user interaction.**
`welcomeMsg` should be in `index.html`

**Additional context**
Will also need to move to `domUpdates.js`

### PR DESCRIPTION
**Pull request by alia-peterson**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [ ] Adds a new feature
- [x] Improves an existing feature
- [x] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*
Renamed html element classes to better follow BEM guidelines

## *Instructions for reviewer:*
*Where should the reviewer start?* 
index.html
*How should this be manually tested?*
Check that all functionality is working
*Any background context you want to provide?*
I realized that the recipeData array and the recipe API have different properties so we'll need to revise some of the fetch methods to incorporate all relevant data. I revised the code to save a local copy of all recipes but we still need to update references throughout the code that still use the data file. Couldn't do this yet because of the aforementioned inconsistencies between the datasets. 
*What are the relevant tickets?*
Closes #20

## *Issues:*
No known issues

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -52,22 +49,23 @@ function generateUser() {
 
 // CREATE RECIPE CARDS
 function createCards() {
-  fetch('http://localhost:3001/api/v1/recipes')
+  return fetch('http://localhost:3001/api/v1/recipes')
```
Comment (tashiad) [inline src/scripts.js:52]: Wonder why it was necessary to `return` the `fetch` -- didn't know that was a thing!

File: src/scripts.js [hunk 2]
```diff
@@ -103,10 +101,10 @@ function findCheckedBoxes() {
 function findTaggedRecipes(selected) {
   let filteredResults = [];
   selected.forEach(tag => {
-    let allRecipes = recipes.filter(recipe => {
+    let recipeData = recipes.filter(recipe => {
```
Comment (tashiad) [inline src/scripts.js:104]: Should `recipes` be `allRecipes`? Since it looks like you changed the name of that array global variable.

**Review by tashiad — COMMENTED** [review]
Made a couple of comments, will hold off on approval until we discuss how to fix discrepancies between the recipeData array and the recipe API.

File: src/scripts.js (hunk 1 above)
Comment (alia-peterson) [reply src/scripts.js:52]: I ended up returning it so that i could do a .then() in the page load function (line 29 of scripts.js). Otherwise the findTags() function would execute before the API was done fetching. It isn't really necessary at this point since the recipe data is still being populated by the data file but I realized that was going to be an issue in the future!

File: src/scripts.js (hunk 2 above)
Comment (alia-peterson) [reply src/scripts.js:104]: Eventually yes. I started to change things over and then it became a painful process. So for now most of the references are using the data file and will have to be migrated over to the API still. This was part of the issue i was mentioning where the API doesn't have the same properties, so it'll be a bit of a process to make sure that all of the array functions are able to access the correct information.

**Review by tashiad — APPROVED** [review]

**Review by richardltyler — APPROVED** [review]
You addressed all of the questions that I had in the above comments
